//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DummyDataCreator
{
    public partial class BlocksForExecution
    {
        #region Primitive Properties
    
        public virtual int BlockID
        {
            get;
            set;
        }
    
        public virtual int TraderID
        {
            get;
            set;
        }
    
        public virtual int SecurityID
        {
            get;
            set;
        }
    
        public virtual string BlockSide
        {
            get;
            set;
        }
    
        public virtual int BlockStatus
        {
            get;
            set;
        }
    
        public virtual decimal LimitPrice
        {
            get;
            set;
        }
    
        public virtual decimal StopPrice
        {
            get;
            set;
        }
    
        public virtual int TotalQuantity
        {
            get;
            set;
        }
    
        public virtual int ExecutedQuantity
        {
            get;
            set;
        }
    
        public virtual int OpenQuantity
        {
            get;
            set;
        }

        #endregion
    }
}
