//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ExecutionTraderDataAccessLayer
{
    public partial class Security
    {
        #region Primitive Properties
    
        public virtual int SecurityID
        {
            get;
            set;
        }
    
        public virtual string SecurityName
        {
            get;
            set;
        }
    
        public virtual string SecuritySymbol
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> LastTradedPrice
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Block> Blocks
        {
            get
            {
                if (_blocks == null)
                {
                    var newCollection = new FixupCollection<Block>();
                    newCollection.CollectionChanged += FixupBlocks;
                    _blocks = newCollection;
                }
                return _blocks;
            }
            set
            {
                if (!ReferenceEquals(_blocks, value))
                {
                    var previousValue = _blocks as FixupCollection<Block>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupBlocks;
                    }
                    _blocks = value;
                    var newValue = value as FixupCollection<Block>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupBlocks;
                    }
                }
            }
        }
        private ICollection<Block> _blocks;
    
        public virtual ICollection<Order> Orders
        {
            get
            {
                if (_orders == null)
                {
                    var newCollection = new FixupCollection<Order>();
                    newCollection.CollectionChanged += FixupOrders;
                    _orders = newCollection;
                }
                return _orders;
            }
            set
            {
                if (!ReferenceEquals(_orders, value))
                {
                    var previousValue = _orders as FixupCollection<Order>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupOrders;
                    }
                    _orders = value;
                    var newValue = value as FixupCollection<Order>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupOrders;
                    }
                }
            }
        }
        private ICollection<Order> _orders;
    
        public virtual ICollection<ProposedBlock> ProposedBlocks
        {
            get
            {
                if (_proposedBlocks == null)
                {
                    var newCollection = new FixupCollection<ProposedBlock>();
                    newCollection.CollectionChanged += FixupProposedBlocks;
                    _proposedBlocks = newCollection;
                }
                return _proposedBlocks;
            }
            set
            {
                if (!ReferenceEquals(_proposedBlocks, value))
                {
                    var previousValue = _proposedBlocks as FixupCollection<ProposedBlock>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupProposedBlocks;
                    }
                    _proposedBlocks = value;
                    var newValue = value as FixupCollection<ProposedBlock>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupProposedBlocks;
                    }
                }
            }
        }
        private ICollection<ProposedBlock> _proposedBlocks;
    
        public virtual ICollection<SecurityConfigurationDetail> SecurityConfigurationDetails
        {
            get
            {
                if (_securityConfigurationDetails == null)
                {
                    var newCollection = new FixupCollection<SecurityConfigurationDetail>();
                    newCollection.CollectionChanged += FixupSecurityConfigurationDetails;
                    _securityConfigurationDetails = newCollection;
                }
                return _securityConfigurationDetails;
            }
            set
            {
                if (!ReferenceEquals(_securityConfigurationDetails, value))
                {
                    var previousValue = _securityConfigurationDetails as FixupCollection<SecurityConfigurationDetail>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSecurityConfigurationDetails;
                    }
                    _securityConfigurationDetails = value;
                    var newValue = value as FixupCollection<SecurityConfigurationDetail>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSecurityConfigurationDetails;
                    }
                }
            }
        }
        private ICollection<SecurityConfigurationDetail> _securityConfigurationDetails;

        #endregion
        #region Association Fixup
    
        private void FixupBlocks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Block item in e.NewItems)
                {
                    item.Security = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Block item in e.OldItems)
                {
                    if (ReferenceEquals(item.Security, this))
                    {
                        item.Security = null;
                    }
                }
            }
        }
    
        private void FixupOrders(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Order item in e.NewItems)
                {
                    item.Security = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Order item in e.OldItems)
                {
                    if (ReferenceEquals(item.Security, this))
                    {
                        item.Security = null;
                    }
                }
            }
        }
    
        private void FixupProposedBlocks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ProposedBlock item in e.NewItems)
                {
                    item.Security = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProposedBlock item in e.OldItems)
                {
                    if (ReferenceEquals(item.Security, this))
                    {
                        item.Security = null;
                    }
                }
            }
        }
    
        private void FixupSecurityConfigurationDetails(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SecurityConfigurationDetail item in e.NewItems)
                {
                    item.Security = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SecurityConfigurationDetail item in e.OldItems)
                {
                    if (ReferenceEquals(item.Security, this))
                    {
                        item.Security = null;
                    }
                }
            }
        }

        #endregion
    }
}
