//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquityTradingApp.ExecuteBlockServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Block", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Block : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockSideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlockStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.ExecutedBlock[] ExecutedBlocksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LimitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpenQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.OrderAllocation[] OrderAllocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Security SecurityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecurityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StopPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalQuatityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TraderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockSide {
            get {
                return this.BlockSideField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockSideField, value) != true)) {
                    this.BlockSideField = value;
                    this.RaisePropertyChanged("BlockSide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockStatus {
            get {
                return this.BlockStatusField;
            }
            set {
                if ((this.BlockStatusField.Equals(value) != true)) {
                    this.BlockStatusField = value;
                    this.RaisePropertyChanged("BlockStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.ExecutedBlock[] ExecutedBlocks {
            get {
                return this.ExecutedBlocksField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutedBlocksField, value) != true)) {
                    this.ExecutedBlocksField = value;
                    this.RaisePropertyChanged("ExecutedBlocks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutedQuantity {
            get {
                return this.ExecutedQuantityField;
            }
            set {
                if ((this.ExecutedQuantityField.Equals(value) != true)) {
                    this.ExecutedQuantityField = value;
                    this.RaisePropertyChanged("ExecutedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LimitPrice {
            get {
                return this.LimitPriceField;
            }
            set {
                if ((this.LimitPriceField.Equals(value) != true)) {
                    this.LimitPriceField = value;
                    this.RaisePropertyChanged("LimitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpenQuantity {
            get {
                return this.OpenQuantityField;
            }
            set {
                if ((this.OpenQuantityField.Equals(value) != true)) {
                    this.OpenQuantityField = value;
                    this.RaisePropertyChanged("OpenQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.OrderAllocation[] OrderAllocations {
            get {
                return this.OrderAllocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderAllocationsField, value) != true)) {
                    this.OrderAllocationsField = value;
                    this.RaisePropertyChanged("OrderAllocations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Security Security {
            get {
                return this.SecurityField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityField, value) != true)) {
                    this.SecurityField = value;
                    this.RaisePropertyChanged("Security");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecurityID {
            get {
                return this.SecurityIDField;
            }
            set {
                if ((this.SecurityIDField.Equals(value) != true)) {
                    this.SecurityIDField = value;
                    this.RaisePropertyChanged("SecurityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StopPrice {
            get {
                return this.StopPriceField;
            }
            set {
                if ((this.StopPriceField.Equals(value) != true)) {
                    this.StopPriceField = value;
                    this.RaisePropertyChanged("StopPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalQuatity {
            get {
                return this.TotalQuatityField;
            }
            set {
                if ((this.TotalQuatityField.Equals(value) != true)) {
                    this.TotalQuatityField = value;
                    this.RaisePropertyChanged("TotalQuatity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TraderID {
            get {
                return this.TraderIDField;
            }
            set {
                if ((this.TraderIDField.Equals(value) != true)) {
                    this.TraderIDField = value;
                    this.RaisePropertyChanged("TraderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Security", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Security : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Block[] BlocksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutionQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LastTradedPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MarketPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.ProposedBlock[] ProposedBlocksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.SecurityConfigurationDetail[] SecurityConfigurationDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecurityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecuritySymbolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Block[] Blocks {
            get {
                return this.BlocksField;
            }
            set {
                if ((object.ReferenceEquals(this.BlocksField, value) != true)) {
                    this.BlocksField = value;
                    this.RaisePropertyChanged("Blocks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutionQuantity {
            get {
                return this.ExecutionQuantityField;
            }
            set {
                if ((this.ExecutionQuantityField.Equals(value) != true)) {
                    this.ExecutionQuantityField = value;
                    this.RaisePropertyChanged("ExecutionQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LastTradedPrice {
            get {
                return this.LastTradedPriceField;
            }
            set {
                if ((this.LastTradedPriceField.Equals(value) != true)) {
                    this.LastTradedPriceField = value;
                    this.RaisePropertyChanged("LastTradedPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MarketPrice {
            get {
                return this.MarketPriceField;
            }
            set {
                if ((this.MarketPriceField.Equals(value) != true)) {
                    this.MarketPriceField = value;
                    this.RaisePropertyChanged("MarketPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.ProposedBlock[] ProposedBlocks {
            get {
                return this.ProposedBlocksField;
            }
            set {
                if ((object.ReferenceEquals(this.ProposedBlocksField, value) != true)) {
                    this.ProposedBlocksField = value;
                    this.RaisePropertyChanged("ProposedBlocks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.SecurityConfigurationDetail[] SecurityConfigurationDetails {
            get {
                return this.SecurityConfigurationDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityConfigurationDetailsField, value) != true)) {
                    this.SecurityConfigurationDetailsField = value;
                    this.RaisePropertyChanged("SecurityConfigurationDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecurityID {
            get {
                return this.SecurityIDField;
            }
            set {
                if ((this.SecurityIDField.Equals(value) != true)) {
                    this.SecurityIDField = value;
                    this.RaisePropertyChanged("SecurityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityName {
            get {
                return this.SecurityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityNameField, value) != true)) {
                    this.SecurityNameField = value;
                    this.RaisePropertyChanged("SecurityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecuritySymbol {
            get {
                return this.SecuritySymbolField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuritySymbolField, value) != true)) {
                    this.SecuritySymbolField = value;
                    this.RaisePropertyChanged("SecuritySymbol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutedBlock", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class ExecutedBlock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Block BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutedBlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.OrderAllocation[] OrderAllocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TransactionPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Block Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutedBlockID {
            get {
                return this.ExecutedBlockIDField;
            }
            set {
                if ((this.ExecutedBlockIDField.Equals(value) != true)) {
                    this.ExecutedBlockIDField = value;
                    this.RaisePropertyChanged("ExecutedBlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutedQuantity {
            get {
                return this.ExecutedQuantityField;
            }
            set {
                if ((this.ExecutedQuantityField.Equals(value) != true)) {
                    this.ExecutedQuantityField = value;
                    this.RaisePropertyChanged("ExecutedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.OrderAllocation[] OrderAllocations {
            get {
                return this.OrderAllocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderAllocationsField, value) != true)) {
                    this.OrderAllocationsField = value;
                    this.RaisePropertyChanged("OrderAllocations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransactionPrice {
            get {
                return this.TransactionPriceField;
            }
            set {
                if ((this.TransactionPriceField.Equals(value) != true)) {
                    this.TransactionPriceField = value;
                    this.RaisePropertyChanged("TransactionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionTime {
            get {
                return this.TransactionTimeField;
            }
            set {
                if ((this.TransactionTimeField.Equals(value) != true)) {
                    this.TransactionTimeField = value;
                    this.RaisePropertyChanged("TransactionTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderAllocation", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class OrderAllocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllocatedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllocationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Block BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.ExecutedBlock ExecutedBlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExecutionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TransactionFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TransactionPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllocatedQuantity {
            get {
                return this.AllocatedQuantityField;
            }
            set {
                if ((this.AllocatedQuantityField.Equals(value) != true)) {
                    this.AllocatedQuantityField = value;
                    this.RaisePropertyChanged("AllocatedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllocationID {
            get {
                return this.AllocationIDField;
            }
            set {
                if ((this.AllocationIDField.Equals(value) != true)) {
                    this.AllocationIDField = value;
                    this.RaisePropertyChanged("AllocationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Block Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.ExecutedBlock ExecutedBlock {
            get {
                return this.ExecutedBlockField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutedBlockField, value) != true)) {
                    this.ExecutedBlockField = value;
                    this.RaisePropertyChanged("ExecutedBlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExecutionID {
            get {
                return this.ExecutionIDField;
            }
            set {
                if ((this.ExecutionIDField.Equals(value) != true)) {
                    this.ExecutionIDField = value;
                    this.RaisePropertyChanged("ExecutionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransactionFee {
            get {
                return this.TransactionFeeField;
            }
            set {
                if ((this.TransactionFeeField.Equals(value) != true)) {
                    this.TransactionFeeField = value;
                    this.RaisePropertyChanged("TransactionFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransactionPrice {
            get {
                return this.TransactionPriceField;
            }
            set {
                if ((this.TransactionPriceField.Equals(value) != true)) {
                    this.TransactionPriceField = value;
                    this.RaisePropertyChanged("TransactionPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AllocatedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Block BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BookTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LimitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManagerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> NotifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpenQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.OrderAllocation[] OrderAllocationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderQualifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Portfolio PortfolioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortfolioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Security SecurityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecurityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StopPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TraderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TransactionPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TransactionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.User User1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountTypeField, value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AllocatedQuantity {
            get {
                return this.AllocatedQuantityField;
            }
            set {
                if ((this.AllocatedQuantityField.Equals(value) != true)) {
                    this.AllocatedQuantityField = value;
                    this.RaisePropertyChanged("AllocatedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Block Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BlockID {
            get {
                return this.BlockIDField;
            }
            set {
                if ((this.BlockIDField.Equals(value) != true)) {
                    this.BlockIDField = value;
                    this.RaisePropertyChanged("BlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BookTime {
            get {
                return this.BookTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.BookTimeField, value) != true)) {
                    this.BookTimeField = value;
                    this.RaisePropertyChanged("BookTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LimitPrice {
            get {
                return this.LimitPriceField;
            }
            set {
                if ((this.LimitPriceField.Equals(value) != true)) {
                    this.LimitPriceField = value;
                    this.RaisePropertyChanged("LimitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerID {
            get {
                return this.ManagerIDField;
            }
            set {
                if ((this.ManagerIDField.Equals(value) != true)) {
                    this.ManagerIDField = value;
                    this.RaisePropertyChanged("ManagerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Notify {
            get {
                return this.NotifyField;
            }
            set {
                if ((this.NotifyField.Equals(value) != true)) {
                    this.NotifyField = value;
                    this.RaisePropertyChanged("Notify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpenQuantity {
            get {
                return this.OpenQuantityField;
            }
            set {
                if ((this.OpenQuantityField.Equals(value) != true)) {
                    this.OpenQuantityField = value;
                    this.RaisePropertyChanged("OpenQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.OrderAllocation[] OrderAllocations {
            get {
                return this.OrderAllocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderAllocationsField, value) != true)) {
                    this.OrderAllocationsField = value;
                    this.RaisePropertyChanged("OrderAllocations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderQualifier {
            get {
                return this.OrderQualifierField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderQualifierField, value) != true)) {
                    this.OrderQualifierField = value;
                    this.RaisePropertyChanged("OrderQualifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType {
            get {
                return this.OrderTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderTypeField, value) != true)) {
                    this.OrderTypeField = value;
                    this.RaisePropertyChanged("OrderType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Portfolio Portfolio {
            get {
                return this.PortfolioField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioField, value) != true)) {
                    this.PortfolioField = value;
                    this.RaisePropertyChanged("Portfolio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PortfolioID {
            get {
                return this.PortfolioIDField;
            }
            set {
                if ((this.PortfolioIDField.Equals(value) != true)) {
                    this.PortfolioIDField = value;
                    this.RaisePropertyChanged("PortfolioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Security Security {
            get {
                return this.SecurityField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityField, value) != true)) {
                    this.SecurityField = value;
                    this.RaisePropertyChanged("Security");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecurityID {
            get {
                return this.SecurityIDField;
            }
            set {
                if ((this.SecurityIDField.Equals(value) != true)) {
                    this.SecurityIDField = value;
                    this.RaisePropertyChanged("SecurityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Side {
            get {
                return this.SideField;
            }
            set {
                if ((object.ReferenceEquals(this.SideField, value) != true)) {
                    this.SideField = value;
                    this.RaisePropertyChanged("Side");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StopPrice {
            get {
                return this.StopPriceField;
            }
            set {
                if ((this.StopPriceField.Equals(value) != true)) {
                    this.StopPriceField = value;
                    this.RaisePropertyChanged("StopPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalQuantity {
            get {
                return this.TotalQuantityField;
            }
            set {
                if ((this.TotalQuantityField.Equals(value) != true)) {
                    this.TotalQuantityField = value;
                    this.RaisePropertyChanged("TotalQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TraderID {
            get {
                return this.TraderIDField;
            }
            set {
                if ((this.TraderIDField.Equals(value) != true)) {
                    this.TraderIDField = value;
                    this.RaisePropertyChanged("TraderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TransactionPrice {
            get {
                return this.TransactionPriceField;
            }
            set {
                if ((this.TransactionPriceField.Equals(value) != true)) {
                    this.TransactionPriceField = value;
                    this.RaisePropertyChanged("TransactionPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TransactionTime {
            get {
                return this.TransactionTimeField;
            }
            set {
                if ((this.TransactionTimeField.Equals(value) != true)) {
                    this.TransactionTimeField = value;
                    this.RaisePropertyChanged("TransactionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.User User1 {
            get {
                return this.User1Field;
            }
            set {
                if ((object.ReferenceEquals(this.User1Field, value) != true)) {
                    this.User1Field = value;
                    this.RaisePropertyChanged("User1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Portfolio[] PortfoliosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Portfolio[] Portfolios {
            get {
                return this.PortfoliosField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfoliosField, value) != true)) {
                    this.PortfoliosField = value;
                    this.RaisePropertyChanged("Portfolios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Portfolio", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Portfolio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortfolioIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortfolioNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PortfolioID {
            get {
                return this.PortfolioIDField;
            }
            set {
                if ((this.PortfolioIDField.Equals(value) != true)) {
                    this.PortfolioIDField = value;
                    this.RaisePropertyChanged("PortfolioID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortfolioName {
            get {
                return this.PortfolioNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfolioNameField, value) != true)) {
                    this.PortfolioNameField = value;
                    this.RaisePropertyChanged("PortfolioName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class Status : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusName {
            get {
                return this.StatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNameField, value) != true)) {
                    this.StatusNameField = value;
                    this.RaisePropertyChanged("StatusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Order[] Orders1 {
            get {
                return this.Orders1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Orders1Field, value) != true)) {
                    this.Orders1Field = value;
                    this.RaisePropertyChanged("Orders1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProposedBlock", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class ProposedBlock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockSideField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LimitPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProposedBlockIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Security SecurityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecurityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal StopPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockSide {
            get {
                return this.BlockSideField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockSideField, value) != true)) {
                    this.BlockSideField = value;
                    this.RaisePropertyChanged("BlockSide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LimitPrice {
            get {
                return this.LimitPriceField;
            }
            set {
                if ((this.LimitPriceField.Equals(value) != true)) {
                    this.LimitPriceField = value;
                    this.RaisePropertyChanged("LimitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProposedBlockID {
            get {
                return this.ProposedBlockIDField;
            }
            set {
                if ((this.ProposedBlockIDField.Equals(value) != true)) {
                    this.ProposedBlockIDField = value;
                    this.RaisePropertyChanged("ProposedBlockID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Security Security {
            get {
                return this.SecurityField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityField, value) != true)) {
                    this.SecurityField = value;
                    this.RaisePropertyChanged("Security");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecurityID {
            get {
                return this.SecurityIDField;
            }
            set {
                if ((this.SecurityIDField.Equals(value) != true)) {
                    this.SecurityIDField = value;
                    this.RaisePropertyChanged("SecurityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StopPrice {
            get {
                return this.StopPriceField;
            }
            set {
                if ((this.StopPriceField.Equals(value) != true)) {
                    this.StopPriceField = value;
                    this.RaisePropertyChanged("StopPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalQuantity {
            get {
                return this.TotalQuantityField;
            }
            set {
                if ((this.TotalQuantityField.Equals(value) != true)) {
                    this.TotalQuantityField = value;
                    this.RaisePropertyChanged("TotalQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityConfigurationDetail", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class SecurityConfigurationDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FullyExecutedOrderProbabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] MaxExecutionIntervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxExecutionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPriceSpreadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EquityTradingApp.ExecuteBlockServiceReference.Security SecurityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecurityConfigurationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecurityIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FullyExecutedOrderProbability {
            get {
                return this.FullyExecutedOrderProbabilityField;
            }
            set {
                if ((this.FullyExecutedOrderProbabilityField.Equals(value) != true)) {
                    this.FullyExecutedOrderProbabilityField = value;
                    this.RaisePropertyChanged("FullyExecutedOrderProbability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MaxExecutionInterval {
            get {
                return this.MaxExecutionIntervalField;
            }
            set {
                if ((object.ReferenceEquals(this.MaxExecutionIntervalField, value) != true)) {
                    this.MaxExecutionIntervalField = value;
                    this.RaisePropertyChanged("MaxExecutionInterval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxExecutionNumber {
            get {
                return this.MaxExecutionNumberField;
            }
            set {
                if ((this.MaxExecutionNumberField.Equals(value) != true)) {
                    this.MaxExecutionNumberField = value;
                    this.RaisePropertyChanged("MaxExecutionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPriceSpread {
            get {
                return this.MaxPriceSpreadField;
            }
            set {
                if ((this.MaxPriceSpreadField.Equals(value) != true)) {
                    this.MaxPriceSpreadField = value;
                    this.RaisePropertyChanged("MaxPriceSpread");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EquityTradingApp.ExecuteBlockServiceReference.Security Security {
            get {
                return this.SecurityField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityField, value) != true)) {
                    this.SecurityField = value;
                    this.RaisePropertyChanged("Security");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecurityConfigurationID {
            get {
                return this.SecurityConfigurationIDField;
            }
            set {
                if ((this.SecurityConfigurationIDField.Equals(value) != true)) {
                    this.SecurityConfigurationIDField = value;
                    this.RaisePropertyChanged("SecurityConfigurationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecurityID {
            get {
                return this.SecurityIDField;
            }
            set {
                if ((this.SecurityIDField.Equals(value) != true)) {
                    this.SecurityIDField = value;
                    this.RaisePropertyChanged("SecurityID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmationMessage", Namespace="http://schemas.datacontract.org/2004/07/AutoAllocationService")]
    [System.SerializableAttribute()]
    public partial class ConfirmationMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExecuteBlockServiceReference.IExecuteBlockService")]
    public interface IExecuteBlockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecuteBlockService/ExecuteBlock", ReplyAction="http://tempuri.org/IExecuteBlockService/ExecuteBlockResponse")]
        EquityTradingApp.ExecuteBlockServiceReference.ConfirmationMessage ExecuteBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockList);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IExecuteBlockService/ExecuteBlock", ReplyAction="http://tempuri.org/IExecuteBlockService/ExecuteBlockResponse")]
        System.IAsyncResult BeginExecuteBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockList, System.AsyncCallback callback, object asyncState);
        
        EquityTradingApp.ExecuteBlockServiceReference.ConfirmationMessage EndExecuteBlock(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecuteBlockService/ExecutionOfBlock", ReplyAction="http://tempuri.org/IExecuteBlockService/ExecutionOfBlockResponse")]
        void ExecutionOfBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockListToExecute);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IExecuteBlockService/ExecutionOfBlock", ReplyAction="http://tempuri.org/IExecuteBlockService/ExecutionOfBlockResponse")]
        System.IAsyncResult BeginExecutionOfBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockListToExecute, System.AsyncCallback callback, object asyncState);
        
        void EndExecutionOfBlock(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExecuteBlockService/Polling", ReplyAction="http://tempuri.org/IExecuteBlockService/PollingResponse")]
        void Polling();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IExecuteBlockService/Polling", ReplyAction="http://tempuri.org/IExecuteBlockService/PollingResponse")]
        System.IAsyncResult BeginPolling(System.AsyncCallback callback, object asyncState);
        
        void EndPolling(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExecuteBlockServiceChannel : EquityTradingApp.ExecuteBlockServiceReference.IExecuteBlockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteBlockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExecuteBlockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public EquityTradingApp.ExecuteBlockServiceReference.ConfirmationMessage Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((EquityTradingApp.ExecuteBlockServiceReference.ConfirmationMessage)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecuteBlockServiceClient : System.ServiceModel.ClientBase<EquityTradingApp.ExecuteBlockServiceReference.IExecuteBlockService>, EquityTradingApp.ExecuteBlockServiceReference.IExecuteBlockService {
        
        private BeginOperationDelegate onBeginExecuteBlockDelegate;
        
        private EndOperationDelegate onEndExecuteBlockDelegate;
        
        private System.Threading.SendOrPostCallback onExecuteBlockCompletedDelegate;
        
        private BeginOperationDelegate onBeginExecutionOfBlockDelegate;
        
        private EndOperationDelegate onEndExecutionOfBlockDelegate;
        
        private System.Threading.SendOrPostCallback onExecutionOfBlockCompletedDelegate;
        
        private BeginOperationDelegate onBeginPollingDelegate;
        
        private EndOperationDelegate onEndPollingDelegate;
        
        private System.Threading.SendOrPostCallback onPollingCompletedDelegate;
        
        public ExecuteBlockServiceClient() {
        }
        
        public ExecuteBlockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecuteBlockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteBlockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecuteBlockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ExecuteBlockCompletedEventArgs> ExecuteBlockCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ExecutionOfBlockCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PollingCompleted;
        
        public EquityTradingApp.ExecuteBlockServiceReference.ConfirmationMessage ExecuteBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockList) {
            return base.Channel.ExecuteBlock(blockList);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExecuteBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecuteBlock(blockList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public EquityTradingApp.ExecuteBlockServiceReference.ConfirmationMessage EndExecuteBlock(System.IAsyncResult result) {
            return base.Channel.EndExecuteBlock(result);
        }
        
        private System.IAsyncResult OnBeginExecuteBlock(object[] inValues, System.AsyncCallback callback, object asyncState) {
            EquityTradingApp.ExecuteBlockServiceReference.Block[] blockList = ((EquityTradingApp.ExecuteBlockServiceReference.Block[])(inValues[0]));
            return this.BeginExecuteBlock(blockList, callback, asyncState);
        }
        
        private object[] OnEndExecuteBlock(System.IAsyncResult result) {
            EquityTradingApp.ExecuteBlockServiceReference.ConfirmationMessage retVal = this.EndExecuteBlock(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExecuteBlockCompleted(object state) {
            if ((this.ExecuteBlockCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecuteBlockCompleted(this, new ExecuteBlockCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecuteBlockAsync(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockList) {
            this.ExecuteBlockAsync(blockList, null);
        }
        
        public void ExecuteBlockAsync(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockList, object userState) {
            if ((this.onBeginExecuteBlockDelegate == null)) {
                this.onBeginExecuteBlockDelegate = new BeginOperationDelegate(this.OnBeginExecuteBlock);
            }
            if ((this.onEndExecuteBlockDelegate == null)) {
                this.onEndExecuteBlockDelegate = new EndOperationDelegate(this.OnEndExecuteBlock);
            }
            if ((this.onExecuteBlockCompletedDelegate == null)) {
                this.onExecuteBlockCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteBlockCompleted);
            }
            base.InvokeAsync(this.onBeginExecuteBlockDelegate, new object[] {
                        blockList}, this.onEndExecuteBlockDelegate, this.onExecuteBlockCompletedDelegate, userState);
        }
        
        public void ExecutionOfBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockListToExecute) {
            base.Channel.ExecutionOfBlock(blockListToExecute);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginExecutionOfBlock(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockListToExecute, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExecutionOfBlock(blockListToExecute, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndExecutionOfBlock(System.IAsyncResult result) {
            base.Channel.EndExecutionOfBlock(result);
        }
        
        private System.IAsyncResult OnBeginExecutionOfBlock(object[] inValues, System.AsyncCallback callback, object asyncState) {
            EquityTradingApp.ExecuteBlockServiceReference.Block[] blockListToExecute = ((EquityTradingApp.ExecuteBlockServiceReference.Block[])(inValues[0]));
            return this.BeginExecutionOfBlock(blockListToExecute, callback, asyncState);
        }
        
        private object[] OnEndExecutionOfBlock(System.IAsyncResult result) {
            this.EndExecutionOfBlock(result);
            return null;
        }
        
        private void OnExecutionOfBlockCompleted(object state) {
            if ((this.ExecutionOfBlockCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExecutionOfBlockCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExecutionOfBlockAsync(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockListToExecute) {
            this.ExecutionOfBlockAsync(blockListToExecute, null);
        }
        
        public void ExecutionOfBlockAsync(EquityTradingApp.ExecuteBlockServiceReference.Block[] blockListToExecute, object userState) {
            if ((this.onBeginExecutionOfBlockDelegate == null)) {
                this.onBeginExecutionOfBlockDelegate = new BeginOperationDelegate(this.OnBeginExecutionOfBlock);
            }
            if ((this.onEndExecutionOfBlockDelegate == null)) {
                this.onEndExecutionOfBlockDelegate = new EndOperationDelegate(this.OnEndExecutionOfBlock);
            }
            if ((this.onExecutionOfBlockCompletedDelegate == null)) {
                this.onExecutionOfBlockCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecutionOfBlockCompleted);
            }
            base.InvokeAsync(this.onBeginExecutionOfBlockDelegate, new object[] {
                        blockListToExecute}, this.onEndExecutionOfBlockDelegate, this.onExecutionOfBlockCompletedDelegate, userState);
        }
        
        public void Polling() {
            base.Channel.Polling();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPolling(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPolling(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndPolling(System.IAsyncResult result) {
            base.Channel.EndPolling(result);
        }
        
        private System.IAsyncResult OnBeginPolling(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginPolling(callback, asyncState);
        }
        
        private object[] OnEndPolling(System.IAsyncResult result) {
            this.EndPolling(result);
            return null;
        }
        
        private void OnPollingCompleted(object state) {
            if ((this.PollingCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PollingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PollingAsync() {
            this.PollingAsync(null);
        }
        
        public void PollingAsync(object userState) {
            if ((this.onBeginPollingDelegate == null)) {
                this.onBeginPollingDelegate = new BeginOperationDelegate(this.OnBeginPolling);
            }
            if ((this.onEndPollingDelegate == null)) {
                this.onEndPollingDelegate = new EndOperationDelegate(this.OnEndPolling);
            }
            if ((this.onPollingCompletedDelegate == null)) {
                this.onPollingCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPollingCompleted);
            }
            base.InvokeAsync(this.onBeginPollingDelegate, null, this.onEndPollingDelegate, this.onPollingCompletedDelegate, userState);
        }
    }
}
