//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MockProjectDBModel", "FK_Order_Block", "Block", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccessLayer.Block), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Order), true)]
[assembly: EdmRelationshipAttribute("MockProjectDBModel", "FK_Client_Portfolio", "Portfolio", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccessLayer.Portfolio), "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Client), true)]
[assembly: EdmRelationshipAttribute("MockProjectDBModel", "FK_Order_Status", "Status", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccessLayer.Status), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Order), true)]
[assembly: EdmRelationshipAttribute("MockProjectDBModel", "FK_Order_Stock", "Stock", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccessLayer.Stock), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.Order), true)]
[assembly: EdmRelationshipAttribute("MockProjectDBModel", "FK_User_Role", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccessLayer.Role), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccessLayer.User), true)]

#endregion

namespace DataAccessLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MockProjectDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MockProjectDBEntities object using the connection string found in the 'MockProjectDBEntities' section of the application configuration file.
        /// </summary>
        public MockProjectDBEntities() : base("name=MockProjectDBEntities", "MockProjectDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MockProjectDBEntities object.
        /// </summary>
        public MockProjectDBEntities(string connectionString) : base(connectionString, "MockProjectDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MockProjectDBEntities object.
        /// </summary>
        public MockProjectDBEntities(EntityConnection connection) : base(connection, "MockProjectDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Block> Blocks
        {
            get
            {
                if ((_Blocks == null))
                {
                    _Blocks = base.CreateObjectSet<Block>("Blocks");
                }
                return _Blocks;
            }
        }
        private ObjectSet<Block> _Blocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Client>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Client> _Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Portfolio> Portfolios
        {
            get
            {
                if ((_Portfolios == null))
                {
                    _Portfolios = base.CreateObjectSet<Portfolio>("Portfolios");
                }
                return _Portfolios;
            }
        }
        private ObjectSet<Portfolio> _Portfolios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Status> Status
        {
            get
            {
                if ((_Status == null))
                {
                    _Status = base.CreateObjectSet<Status>("Status");
                }
                return _Status;
            }
        }
        private ObjectSet<Status> _Status;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Stock> Stocks
        {
            get
            {
                if ((_Stocks == null))
                {
                    _Stocks = base.CreateObjectSet<Stock>("Stocks");
                }
                return _Stocks;
            }
        }
        private ObjectSet<Stock> _Stocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Blocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlocks(Block block)
        {
            base.AddObject("Blocks", block);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Portfolios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPortfolios(Portfolio portfolio)
        {
            base.AddObject("Portfolios", portfolio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Status EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatus(Status status)
        {
            base.AddObject("Status", status);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStocks(Stock stock)
        {
            base.AddObject("Stocks", stock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="Block")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Block : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Block object.
        /// </summary>
        /// <param name="blockID">Initial value of the BlockID property.</param>
        public static Block CreateBlock(global::System.Int32 blockID)
        {
            Block block = new Block();
            block.BlockID = blockID;
            return block;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BlockID
        {
            get
            {
                return _BlockID;
            }
            set
            {
                if (_BlockID != value)
                {
                    OnBlockIDChanging(value);
                    ReportPropertyChanging("BlockID");
                    _BlockID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BlockID");
                    OnBlockIDChanged();
                }
            }
        }
        private global::System.Int32 _BlockID;
        partial void OnBlockIDChanging(global::System.Int32 value);
        partial void OnBlockIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Side
        {
            get
            {
                return _Side;
            }
            set
            {
                OnSideChanging(value);
                ReportPropertyChanging("Side");
                _Side = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Side");
                OnSideChanged();
            }
        }
        private global::System.String _Side;
        partial void OnSideChanging(global::System.String value);
        partial void OnSideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalQuantity
        {
            get
            {
                return _TotalQuantity;
            }
            set
            {
                OnTotalQuantityChanging(value);
                ReportPropertyChanging("TotalQuantity");
                _TotalQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalQuantity");
                OnTotalQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalQuantity;
        partial void OnTotalQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnTotalQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OpenQuantity
        {
            get
            {
                return _OpenQuantity;
            }
            set
            {
                OnOpenQuantityChanging(value);
                ReportPropertyChanging("OpenQuantity");
                _OpenQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpenQuantity");
                OnOpenQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _OpenQuantity;
        partial void OnOpenQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnOpenQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AllocatedQuantity
        {
            get
            {
                return _AllocatedQuantity;
            }
            set
            {
                OnAllocatedQuantityChanging(value);
                ReportPropertyChanging("AllocatedQuantity");
                _AllocatedQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllocatedQuantity");
                OnAllocatedQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _AllocatedQuantity;
        partial void OnAllocatedQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnAllocatedQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StopPrice
        {
            get
            {
                return _StopPrice;
            }
            set
            {
                OnStopPriceChanging(value);
                ReportPropertyChanging("StopPrice");
                _StopPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StopPrice");
                OnStopPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _StopPrice;
        partial void OnStopPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnStopPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LimitPrice
        {
            get
            {
                return _LimitPrice;
            }
            set
            {
                OnLimitPriceChanging(value);
                ReportPropertyChanging("LimitPrice");
                _LimitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimitPrice");
                OnLimitPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _LimitPrice;
        partial void OnLimitPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnLimitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Orders
        {
            get
            {
                return _Orders;
            }
            set
            {
                OnOrdersChanging(value);
                ReportPropertyChanging("Orders");
                _Orders = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Orders");
                OnOrdersChanged();
            }
        }
        private global::System.String _Orders;
        partial void OnOrdersChanging(global::System.String value);
        partial void OnOrdersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusId
        {
            get
            {
                return _StatusId;
            }
            set
            {
                OnStatusIdChanging(value);
                ReportPropertyChanging("StatusId");
                _StatusId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusId");
                OnStatusIdChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusId;
        partial void OnStatusIdChanging(Nullable<global::System.Int32> value);
        partial void OnStatusIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Order_Block", "Order")]
        public EntityCollection<Order> Orders1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("MockProjectDBModel.FK_Order_Block", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("MockProjectDBModel.FK_Order_Block", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="client_ID">Initial value of the Client_ID property.</param>
        public static Client CreateClient(global::System.Int32 client_ID)
        {
            Client client = new Client();
            client.Client_ID = client_ID;
            return client;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Client_ID
        {
            get
            {
                return _Client_ID;
            }
            set
            {
                if (_Client_ID != value)
                {
                    OnClient_IDChanging(value);
                    ReportPropertyChanging("Client_ID");
                    _Client_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Client_ID");
                    OnClient_IDChanged();
                }
            }
        }
        private global::System.Int32 _Client_ID;
        partial void OnClient_IDChanging(global::System.Int32 value);
        partial void OnClient_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClientName
        {
            get
            {
                return _ClientName;
            }
            set
            {
                OnClientNameChanging(value);
                ReportPropertyChanging("ClientName");
                _ClientName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ClientName");
                OnClientNameChanged();
            }
        }
        private global::System.String _ClientName;
        partial void OnClientNameChanging(global::System.String value);
        partial void OnClientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> P_ID
        {
            get
            {
                return _P_ID;
            }
            set
            {
                OnP_IDChanging(value);
                ReportPropertyChanging("P_ID");
                _P_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("P_ID");
                OnP_IDChanged();
            }
        }
        private Nullable<global::System.Int32> _P_ID;
        partial void OnP_IDChanging(Nullable<global::System.Int32> value);
        partial void OnP_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Client_Portfolio", "Portfolio")]
        public Portfolio Portfolio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Portfolio>("MockProjectDBModel.FK_Client_Portfolio", "Portfolio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Portfolio>("MockProjectDBModel.FK_Client_Portfolio", "Portfolio").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Portfolio> PortfolioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Portfolio>("MockProjectDBModel.FK_Client_Portfolio", "Portfolio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Portfolio>("MockProjectDBModel.FK_Client_Portfolio", "Portfolio", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        public static Order CreateOrder(global::System.Int32 orderID)
        {
            Order order = new Order();
            order.OrderID = orderID;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Side
        {
            get
            {
                return _Side;
            }
            set
            {
                OnSideChanging(value);
                ReportPropertyChanging("Side");
                _Side = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Side");
                OnSideChanged();
            }
        }
        private global::System.String _Side;
        partial void OnSideChanging(global::System.String value);
        partial void OnSideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BlockID
        {
            get
            {
                return _BlockID;
            }
            set
            {
                OnBlockIDChanging(value);
                ReportPropertyChanging("BlockID");
                _BlockID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlockID");
                OnBlockIDChanged();
            }
        }
        private Nullable<global::System.Int32> _BlockID;
        partial void OnBlockIDChanging(Nullable<global::System.Int32> value);
        partial void OnBlockIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StockID
        {
            get
            {
                return _StockID;
            }
            set
            {
                OnStockIDChanging(value);
                ReportPropertyChanging("StockID");
                _StockID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StockID");
                OnStockIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StockID;
        partial void OnStockIDChanging(Nullable<global::System.Int32> value);
        partial void OnStockIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusID
        {
            get
            {
                return _StatusID;
            }
            set
            {
                OnStatusIDChanging(value);
                ReportPropertyChanging("StatusID");
                _StatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusID");
                OnStatusIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusID;
        partial void OnStatusIDChanging(Nullable<global::System.Int32> value);
        partial void OnStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Qualifier
        {
            get
            {
                return _Qualifier;
            }
            set
            {
                OnQualifierChanging(value);
                ReportPropertyChanging("Qualifier");
                _Qualifier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Qualifier");
                OnQualifierChanged();
            }
        }
        private global::System.String _Qualifier;
        partial void OnQualifierChanging(global::System.String value);
        partial void OnQualifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OwnedQuantity
        {
            get
            {
                return _OwnedQuantity;
            }
            set
            {
                OnOwnedQuantityChanging(value);
                ReportPropertyChanging("OwnedQuantity");
                _OwnedQuantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnedQuantity");
                OnOwnedQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _OwnedQuantity;
        partial void OnOwnedQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnOwnedQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LimitPrice
        {
            get
            {
                return _LimitPrice;
            }
            set
            {
                OnLimitPriceChanging(value);
                ReportPropertyChanging("LimitPrice");
                _LimitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimitPrice");
                OnLimitPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _LimitPrice;
        partial void OnLimitPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnLimitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> StopPrice
        {
            get
            {
                return _StopPrice;
            }
            set
            {
                OnStopPriceChanging(value);
                ReportPropertyChanging("StopPrice");
                _StopPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StopPrice");
                OnStopPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _StopPrice;
        partial void OnStopPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnStopPriceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Order_Block", "Block")]
        public Block Block
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Block>("MockProjectDBModel.FK_Order_Block", "Block").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Block>("MockProjectDBModel.FK_Order_Block", "Block").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Block> BlockReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Block>("MockProjectDBModel.FK_Order_Block", "Block");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Block>("MockProjectDBModel.FK_Order_Block", "Block", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Order_Status", "Status")]
        public Status Status
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("MockProjectDBModel.FK_Order_Status", "Status").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("MockProjectDBModel.FK_Order_Status", "Status").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Status> StatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Status>("MockProjectDBModel.FK_Order_Status", "Status");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Status>("MockProjectDBModel.FK_Order_Status", "Status", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Order_Stock", "Stock")]
        public Stock Stock
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("MockProjectDBModel.FK_Order_Stock", "Stock").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("MockProjectDBModel.FK_Order_Stock", "Stock").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Stock> StockReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Stock>("MockProjectDBModel.FK_Order_Stock", "Stock");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Stock>("MockProjectDBModel.FK_Order_Stock", "Stock", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="Portfolio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Portfolio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Portfolio object.
        /// </summary>
        /// <param name="p_ID">Initial value of the P_ID property.</param>
        public static Portfolio CreatePortfolio(global::System.Int32 p_ID)
        {
            Portfolio portfolio = new Portfolio();
            portfolio.P_ID = p_ID;
            return portfolio;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 P_ID
        {
            get
            {
                return _P_ID;
            }
            set
            {
                if (_P_ID != value)
                {
                    OnP_IDChanging(value);
                    ReportPropertyChanging("P_ID");
                    _P_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("P_ID");
                    OnP_IDChanged();
                }
            }
        }
        private global::System.Int32 _P_ID;
        partial void OnP_IDChanging(global::System.Int32 value);
        partial void OnP_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String P_Name
        {
            get
            {
                return _P_Name;
            }
            set
            {
                OnP_NameChanging(value);
                ReportPropertyChanging("P_Name");
                _P_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("P_Name");
                OnP_NameChanged();
            }
        }
        private global::System.String _P_Name;
        partial void OnP_NameChanging(global::System.String value);
        partial void OnP_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Client_Portfolio", "Client")]
        public EntityCollection<Client> Clients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Client>("MockProjectDBModel.FK_Client_Portfolio", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Client>("MockProjectDBModel.FK_Client_Portfolio", "Client", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        public static Role CreateRole(global::System.Int32 roleID)
        {
            Role role = new Role();
            role.RoleID = roleID;
            return role;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_User_Role", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("MockProjectDBModel.FK_User_Role", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("MockProjectDBModel.FK_User_Role", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="Status")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Status object.
        /// </summary>
        /// <param name="statusID">Initial value of the StatusID property.</param>
        public static Status CreateStatus(global::System.Int32 statusID)
        {
            Status status = new Status();
            status.StatusID = statusID;
            return status;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusID
        {
            get
            {
                return _StatusID;
            }
            set
            {
                if (_StatusID != value)
                {
                    OnStatusIDChanging(value);
                    ReportPropertyChanging("StatusID");
                    _StatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StatusID");
                    OnStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _StatusID;
        partial void OnStatusIDChanging(global::System.Int32 value);
        partial void OnStatusIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusName
        {
            get
            {
                return _StatusName;
            }
            set
            {
                OnStatusNameChanging(value);
                ReportPropertyChanging("StatusName");
                _StatusName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusName");
                OnStatusNameChanged();
            }
        }
        private global::System.String _StatusName;
        partial void OnStatusNameChanging(global::System.String value);
        partial void OnStatusNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Order_Status", "Order")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("MockProjectDBModel.FK_Order_Status", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("MockProjectDBModel.FK_Order_Status", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="Stock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Stock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Stock object.
        /// </summary>
        /// <param name="stockID">Initial value of the StockID property.</param>
        /// <param name="stockSymbol">Initial value of the StockSymbol property.</param>
        public static Stock CreateStock(global::System.Int32 stockID, global::System.String stockSymbol)
        {
            Stock stock = new Stock();
            stock.StockID = stockID;
            stock.StockSymbol = stockSymbol;
            return stock;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StockID
        {
            get
            {
                return _StockID;
            }
            set
            {
                if (_StockID != value)
                {
                    OnStockIDChanging(value);
                    ReportPropertyChanging("StockID");
                    _StockID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StockID");
                    OnStockIDChanged();
                }
            }
        }
        private global::System.Int32 _StockID;
        partial void OnStockIDChanging(global::System.Int32 value);
        partial void OnStockIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StockSymbol
        {
            get
            {
                return _StockSymbol;
            }
            set
            {
                OnStockSymbolChanging(value);
                ReportPropertyChanging("StockSymbol");
                _StockSymbol = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StockSymbol");
                OnStockSymbolChanged();
            }
        }
        private global::System.String _StockSymbol;
        partial void OnStockSymbolChanging(global::System.String value);
        partial void OnStockSymbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MarketPrice
        {
            get
            {
                return _MarketPrice;
            }
            set
            {
                OnMarketPriceChanging(value);
                ReportPropertyChanging("MarketPrice");
                _MarketPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarketPrice");
                OnMarketPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _MarketPrice;
        partial void OnMarketPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnMarketPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> High
        {
            get
            {
                return _High;
            }
            set
            {
                OnHighChanging(value);
                ReportPropertyChanging("High");
                _High = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("High");
                OnHighChanged();
            }
        }
        private Nullable<global::System.Decimal> _High;
        partial void OnHighChanging(Nullable<global::System.Decimal> value);
        partial void OnHighChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Low
        {
            get
            {
                return _Low;
            }
            set
            {
                OnLowChanging(value);
                ReportPropertyChanging("Low");
                _Low = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Low");
                OnLowChanged();
            }
        }
        private Nullable<global::System.Decimal> _Low;
        partial void OnLowChanging(Nullable<global::System.Decimal> value);
        partial void OnLowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EPS
        {
            get
            {
                return _EPS;
            }
            set
            {
                OnEPSChanging(value);
                ReportPropertyChanging("EPS");
                _EPS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EPS");
                OnEPSChanged();
            }
        }
        private Nullable<global::System.Decimal> _EPS;
        partial void OnEPSChanging(Nullable<global::System.Decimal> value);
        partial void OnEPSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PERatio
        {
            get
            {
                return _PERatio;
            }
            set
            {
                OnPERatioChanging(value);
                ReportPropertyChanging("PERatio");
                _PERatio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PERatio");
                OnPERatioChanged();
            }
        }
        private Nullable<global::System.Decimal> _PERatio;
        partial void OnPERatioChanging(Nullable<global::System.Decimal> value);
        partial void OnPERatioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exchange
        {
            get
            {
                return _Exchange;
            }
            set
            {
                OnExchangeChanging(value);
                ReportPropertyChanging("Exchange");
                _Exchange = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exchange");
                OnExchangeChanged();
            }
        }
        private global::System.String _Exchange;
        partial void OnExchangeChanging(global::System.String value);
        partial void OnExchangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PreviousClose
        {
            get
            {
                return _PreviousClose;
            }
            set
            {
                OnPreviousCloseChanging(value);
                ReportPropertyChanging("PreviousClose");
                _PreviousClose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreviousClose");
                OnPreviousCloseChanged();
            }
        }
        private Nullable<global::System.Decimal> _PreviousClose;
        partial void OnPreviousCloseChanging(Nullable<global::System.Decimal> value);
        partial void OnPreviousCloseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Change
        {
            get
            {
                return _Change;
            }
            set
            {
                OnChangeChanging(value);
                ReportPropertyChanging("Change");
                _Change = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Change");
                OnChangeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Change;
        partial void OnChangeChanging(Nullable<global::System.Decimal> value);
        partial void OnChangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ChangePercent
        {
            get
            {
                return _ChangePercent;
            }
            set
            {
                OnChangePercentChanging(value);
                ReportPropertyChanging("ChangePercent");
                _ChangePercent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ChangePercent");
                OnChangePercentChanged();
            }
        }
        private Nullable<global::System.Decimal> _ChangePercent;
        partial void OnChangePercentChanging(Nullable<global::System.Decimal> value);
        partial void OnChangePercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StockName
        {
            get
            {
                return _StockName;
            }
            set
            {
                OnStockNameChanging(value);
                ReportPropertyChanging("StockName");
                _StockName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StockName");
                OnStockNameChanged();
            }
        }
        private global::System.String _StockName;
        partial void OnStockNameChanging(global::System.String value);
        partial void OnStockNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_Order_Stock", "Order")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("MockProjectDBModel.FK_Order_Stock", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("MockProjectDBModel.FK_Order_Stock", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MockProjectDBModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static User CreateUser(global::System.Int32 userID)
        {
            User user = new User();
            user.UserID = userID;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleID;
        partial void OnRoleIDChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VerificationKey
        {
            get
            {
                return _VerificationKey;
            }
            set
            {
                OnVerificationKeyChanging(value);
                ReportPropertyChanging("VerificationKey");
                _VerificationKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VerificationKey");
                OnVerificationKeyChanged();
            }
        }
        private global::System.String _VerificationKey;
        partial void OnVerificationKeyChanging(global::System.String value);
        partial void OnVerificationKeyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MockProjectDBModel", "FK_User_Role", "Role")]
        public Role Role
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("MockProjectDBModel.FK_User_Role", "Role").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("MockProjectDBModel.FK_User_Role", "Role").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Role> RoleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Role>("MockProjectDBModel.FK_User_Role", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Role>("MockProjectDBModel.FK_User_Role", "Role", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
